import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // MD3 Personal Warm Theme (default)
        'on-primary-container': 'var(--on-primary-container)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'tertiary-container': 'var(--tertiary-container)',
        'surface-tint': 'var(--surface-tint)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'on-error-container': 'var(--on-error-container)',
        'on-surface': 'var(--on-surface)',
        'on-secondary': 'var(--on-secondary)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'primary-fixed': 'var(--primary-fixed)',
        'tertiary': 'var(--tertiary)',
        'surface-container-low': 'var(--surface-container-low)',
        'secondary': 'var(--secondary)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'error-container': 'var(--error-container)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'primary-container': 'var(--primary-container)',
        'outline': 'var(--outline)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'on-tertiary': 'var(--on-tertiary)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'error': 'var(--error)',
        'surface-container': 'var(--surface-container)',
        'secondary-container': 'var(--secondary-container)',
        'primary': 'var(--primary)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        'surface-variant': 'var(--surface-variant)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'background': 'var(--background)',
        'surface': 'var(--surface)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'surface-bright': 'var(--surface-bright)',
        'outline-variant': 'var(--outline-variant)',
        'on-background': 'var(--on-background)',
        'surface-container-high': 'var(--surface-container-high)',
        'on-primary': 'var(--on-primary)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'inverse-surface': 'var(--inverse-surface)',
        'surface-dim': 'var(--surface-dim)',
        'on-error': 'var(--on-error)',
        'inverse-primary': 'var(--inverse-primary)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '20px',
        unit: '4px',
        'sidebar-width': '260px',
        'list-width': '340px',
      },
      fontFamily: {
        'display-serif': ['Newsreader', 'serif'],
        'title-serif': ['Newsreader', 'serif'],
        'body-main': ['Plus Jakarta Sans', 'sans-serif'],
        'body-secondary': ['Plus Jakarta Sans', 'sans-serif'],
        'label-bold': ['Plus Jakarta Sans', 'sans-serif'],
        caption: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-serif': ['32px', { lineHeight: '1.4', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-secondary': ['14px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'body-main': ['16px', { lineHeight: '1.8', letterSpacing: '0.01em', fontWeight: '400' }],
        'title-serif': ['24px', { lineHeight: '1.8', letterSpacing: '0em', fontWeight: '500' }],
        'label-bold': ['13px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.4', letterSpacing: '0em', fontWeight: '400' }],
      },
      boxShadow: {
        ambient: '0px 4px 20px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
}

export default config
