/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTopbar: typeof import('./components/common/AppTopbar.vue')['default']
    CollaborativeTipTapEditor: typeof import('./components/team/CollaborativeTipTapEditor.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMention: typeof import('element-plus/es')['ElMention']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    FileMoveDialog: typeof import('./components/files/FileMoveDialog.vue')['default']
    FileOperationLogsDialog: typeof import('./components/files/FileOperationLogsDialog.vue')['default']
    FileReferencesDialog: typeof import('./components/files/FileReferencesDialog.vue')['default']
    FileUploadSettingsDialog: typeof import('./components/files/FileUploadSettingsDialog.vue')['default']
    GlobalSearchDialog: typeof import('./components/common/GlobalSearchDialog.vue')['default']
    LanguageSwitcher: typeof import('./components/common/LanguageSwitcher.vue')['default']
    LoginWaterBackground: typeof import('./components/shared/LoginWaterBackground.vue')['default']
    NoteFileReferenceDialog: typeof import('./components/notes/NoteFileReferenceDialog.vue')['default']
    NoteHistoryDrawer: typeof import('./components/notes/NoteHistoryDrawer.vue')['default']
    NoteShareDialog: typeof import('./components/notes/NoteShareDialog.vue')['default']
    PersonalSidebar: typeof import('./components/personal/PersonalSidebar.vue')['default']
    ProjectAssociateNotesDialog: typeof import('./components/projects/ProjectAssociateNotesDialog.vue')['default']
    ProjectColorPicker: typeof import('./components/common/ProjectColorPicker.vue')['default']
    ProjectTaskCreateDialog: typeof import('./components/projects/ProjectTaskCreateDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpaceSwitcher: typeof import('./components/common/SpaceSwitcher.vue')['default']
    TaskKanbanBoard: typeof import('./components/team/TaskKanbanBoard.vue')['default']
    TeamSidebar: typeof import('./components/team/TeamSidebar.vue')['default']
    TipTapRichEditor: typeof import('./components/notes/TipTapRichEditor.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
